### PR TITLE
Remove session gradient from main menu settings panel buttons/toggles

### PR DESCRIPTION
**Pull request by dunity**
Remove various session gradient implementations in main menu content, in order to alleviate the lack analogous colors for certain menu faces.

### CODE REVIEW

**Comment by mtschoen-unity** [comment]
Suggestion: for visual polish PRs, we should include a screenshot/gif of the area that changed, with before/after if possible.

**Comment by dunity** [comment]
As a second pass, I've added support for the upper-left to lower-right gradient blending to all custom menu-face buttons (sub-face buttons).  The angled gradient mirrors the blending style/angle of menu face backgrounds, and the menu face icons.  The angled blending (from upper-left, to lower-right),  has an extra bias towards the upper left for better aesthetic appearance.  All custom menu button background graphics have assigned the new SubMenuUIButton material.  In addition, the new AngledVerticalGradientUIClip shader implements an additive color, that brings the chroma & luma in line with that of the menu face background borders (they aren't intended to be as prominent as the menu face icons).
subfacebuttongradients2
subfacebuttongradients

**Comment by dunity** [comment]
@AndrewTHEManeri PR visuals have been updated.

**Comment by AndrewTHEManeri** [comment]
Manual merge successful. performing github merge

**Pull request merged**
