### PR TITLE
Haptic Pulses Editor (and pulse tweaks)

### PR DESCRIPTION
**Pull request by mtschoen-unity**
### Purpose of this PR
Add an editor window for easily tweaking and comparing haptics values.

### Testing status
Tested with current haptic pulses

### Technical risk
None

### Comments to reviewers
Dylan and I had a slight miscommunication about the haptics values. I was telling him that I like certain pulses (hover, etc.) at 4x their current value, but he thought I was saying I wanted the master intensity cranked up to 4. I have adjusted the pulses by dividing everything by 4, setting the master back to 1, and making a few spot adjustments where I thought was appropriate.

Feel free to come back and make more adjustments. The main component of this PR is the editor

### CODE REVIEW

**Comment by dunity** [comment]
The new editor is very helpful. Nice work. Seeing it in action makes me feel like the haptic pulses should be more applicably named now (as to better identify them in the editor window).

**Comment by dunity** [comment]
I pushed a commit that assigns more specific & appropriate naming to haptic pulses, for better display/relevancy in the new pulse editor

**Comment by AndrewTHEManeri** [comment]
Few issues with the menu...
- It needs to be able to undo.  If I set a multiplier to 0, all my assets are hosed currently.
- A 'preview' button next to each of the entries that will play a pulse with the configured duration and intensity would be fantastic for setting this up better.
- It is awkward to set a value and then go back (like multiply by 8 and then by .125) - undo will alleviate this but I feel like we will want another way to doing this non-destructively.  Maybe those master sliders for pulses and intensity that this PR talked about?

**Comment by mtschoen-unity** [comment]
Regarding undo: I tried. I thought that ApplyModifiedProperties was supposed to write to Undo, but maybe I have to dirty the asset, too? I also tried calling IncrementGroup and RecordObjects with no effect. I'll look into it, though.

**Comment by AndrewTHEManeri** [comment]
Manual merge successful, performing github merge

**Pull request merged**
